CREATE TABLE IF NOT EXISTS folders (
  id          SERIAL PRIMARY KEY,
  name        VARCHAR(255) NOT NULL,
  parent_id   INTEGER REFERENCES folders(id) ON DELETE CASCADE,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_by  INTEGER NOT NULL REFERENCES users(id),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
